In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
! mkdir ~/.kaggle

In [ ]:
! cp /content/drive/MyDrive/KaggleAPI/kaggle.json  ~/.kaggle/

In [ ]:
! kaggle datasets download -d uciml/iris

  0% 0.00/3.60k [00:00<?, ?B/s]
100% 3.60k/3.60k [00:00<00:00, 10.6MB/s]


In [ ]:
! unzip /content/iris.zip

Archive:  /content/iris.zip
  inflating: Iris.csv                
  inflating: database.sqlite         


In [ ]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris

In [ ]:
iris=load_iris()

df=pd.DataFrame(data=iris.data, columns=iris.feature_names)
df['target']=iris.target
df.head(5)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [ ]:
sepal_length=np.array(df['sepal length (cm)'])
sepal_length[:5]

array([5.1, 4.9, 4.7, 4.6, 5. ])

In [ ]:
sepal_lengthTarget=np.array([df['target'],df['sepal length (cm)']])
sepal_lengthTarget=sepal_lengthTarget.T
sepal_lengthTarget[:5]

array([[0. , 5.1],
       [0. , 4.9],
       [0. , 4.7],
       [0. , 4.6],
       [0. , 5. ]])

In [ ]:
sepal_lengthTarget.shape

(150, 2)

In [ ]:
sepal_lengthTarget.dtype

dtype('float64')

In [ ]:
np_df=df.values
np_df[:5]

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ],
       [4.6, 3.1, 1.5, 0.2, 0. ],
       [5. , 3.6, 1.4, 0.2, 0. ]])

In [ ]:
np_df.ndim

2

In [ ]:
sepal_length[2]

4.7

In [ ]:
sepal_lengthTarget[3,0]

0.0

In [ ]:
sepal_length[3:20]

array([4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8, 4.3, 5.8, 5.7,
       5.4, 5.1, 5.7, 5.1])

In [ ]:
sepal_length[-4:-1]

array([6.3, 6.5, 6.2])

In [ ]:
sepal_length[-1:-3]

array([], dtype=float64)

In [ ]:
sepal_lengthTarget[0:3,:1]

array([[0.],
       [0.],
       [0.]])

In [ ]:
sepal_lengthTarget[-3:-1,0:]

array([[2. , 6.5],
       [2. , 6.2]])

In [ ]:
sepal_width=np.array(df['sepal width (cm)'])
sepal_width[:5]

array([3.5, 3. , 3.2, 3.1, 3.6])

In [ ]:
sepal_width_sepal_length=sepal_length + sepal_width
sepal_width_sepal_length[:5]

array([8.6, 7.9, 7.9, 7.7, 8.6])

In [ ]:
sepal_area=sepal_length*sepal_width
sepal_area[:5]

array([17.85, 14.7 , 15.04, 14.26, 18.  ])

In [ ]:
sepal_matrix=np.array([df['sepal length (cm)'],df['sepal width (cm)']])
sepal_matrix=sepal_matrix.T
sepal_matrix.shape

(150, 2)

In [ ]:
petal_matrix=np.array([df['petal length (cm)'], df['petal width (cm)']])
petal_matrix.shape

(2, 150)

In [ ]:
np.matmul (sepal_matrix, petal_matrix)

array([[ 7.84,  7.84,  7.33, ..., 33.52, 35.59, 32.31],
       [ 7.46,  7.46,  6.97, ..., 31.48, 33.36, 30.39],
       [ 7.22,  7.22,  6.75, ..., 30.84, 32.74, 29.73],
       ...,
       [ 9.7 ,  9.7 ,  9.05, ..., 39.8 , 42.  , 38.55],
       [ 9.36,  9.36,  8.74, ..., 39.04, 41.3 , 37.74],
       [ 8.86,  8.86,  8.27, ..., 36.68, 38.76, 35.49]])

In [ ]:
sepal_matrix @ petal_matrix

array([[ 7.84,  7.84,  7.33, ..., 33.52, 35.59, 32.31],
       [ 7.46,  7.46,  6.97, ..., 31.48, 33.36, 30.39],
       [ 7.22,  7.22,  6.75, ..., 30.84, 32.74, 29.73],
       ...,
       [ 9.7 ,  9.7 ,  9.05, ..., 39.8 , 42.  , 38.55],
       [ 9.36,  9.36,  8.74, ..., 39.04, 41.3 , 37.74],
       [ 8.86,  8.86,  8.27, ..., 36.68, 38.76, 35.49]])

In [ ]:
np.dot(sepal_matrix, petal_matrix)

array([[ 7.84,  7.84,  7.33, ..., 33.52, 35.59, 32.31],
       [ 7.46,  7.46,  6.97, ..., 31.48, 33.36, 30.39],
       [ 7.22,  7.22,  6.75, ..., 30.84, 32.74, 29.73],
       ...,
       [ 9.7 ,  9.7 ,  9.05, ..., 39.8 , 42.  , 38.55],
       [ 9.36,  9.36,  8.74, ..., 39.04, 41.3 , 37.74],
       [ 8.86,  8.86,  8.27, ..., 36.68, 38.76, 35.49]])

In [ ]:
np.dot (sepal_length, sepal_width)

2673.43

In [ ]:
petal_length=np.array(df[ 'petal length (cm)'])
petal_width=np.array(df['petal width (cm)'])

In [ ]:
temp_length=np.array(sepal_length==petal_length)
temp_length[:5]

array([False, False, False, False, False])

In [ ]:
temp_width=np.array(sepal_width==petal_width)
temp_width[:5]

array([False, False, False, False, False])

In [ ]:
np.array_equal(temp_length, temp_width)

True

In [ ]:
petal_length[petal_length>6]

array([6.6, 6.3, 6.1, 6.7, 6.9, 6.7, 6.1, 6.4, 6.1])

In [ ]:
sepal_width[sepal_width>4]

array([4.4, 4.1, 4.2])

In [ ]:
sepal_width[(sepal_width>2) & (sepal_width<2.5)]

array([2.3, 2.3, 2.4, 2.2, 2.2, 2.4, 2.4, 2.3, 2.3, 2.2])

In [ ]:
np.sum(sepal_length)

876.5

In [ ]:
np.sum(sepal_matrix)

1335.1000000000001

In [ ]:
np.sum(sepal_matrix,axis=0)

array([876.5, 458.6])

In [ ]:
np.sum(sepal_matrix,axis=1)[:5]

array([8.6, 7.9, 7.9, 7.7, 8.6])

In [ ]:
sepal_matrix[:3,:3]

array([[5.1, 3.5],
       [4.9, 3. ],
       [4.7, 3.2]])

In [ ]:
np.mean(sepal_matrix,axis=0)

array([5.84333333, 3.05733333])

In [ ]:
np.sum(sepal_matrix,axis=1)[:5]

array([8.6, 7.9, 7.9, 7.7, 8.6])

In [ ]:
np.min(sepal_matrix)

2.0

In [ ]:
np.argwhere(sepal_matrix>5)[:5]

array([[ 0,  0],
       [ 5,  0],
       [10,  0],
       [14,  0],
       [15,  0]])

In [ ]:
sepal_matrix.sort()
sepal_matrix[:5]

array([[3.5, 5.1],
       [3. , 4.9],
       [3.2, 4.7],
       [3.1, 4.6],
       [3.6, 5. ]])

In [ ]:
np.sort(sepal_matrix)[:5]

array([[3.5, 5.1],
       [3. , 4.9],
       [3.2, 4.7],
       [3.1, 4.6],
       [3.6, 5. ]])

In [ ]:
np.argsort(sepal_matrix)[:5]

array([[0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1]])

In [ ]:
temp=sepal_length[:9]
temp.reshape(3,3)

array([[5.1, 4.9, 4.7],
       [4.6, 5. , 5.4],
       [4.6, 5. , 4.4]])

In [ ]:
temp.flatten()

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4])

In [ ]:
split_arrays=np.split(sepal_matrix,indices_or_sections = [1, 3])
[arr[:2] for arr in split_arrays]

[array([[3.5, 5.1]]),
 array([[3. , 4.9],
        [3.2, 4.7]]),
 array([[3.1, 4.6],
        [3.6, 5. ]])]

In [ ]:
split_arrays=np.split(sepal_matrix,3)
[arr[:2] for arr in split_arrays]

[array([[3.5, 5.1],
        [3. , 4.9]]),
 array([[3.2, 7. ],
        [3.2, 6.4]]),
 array([[3.3, 6.3],
        [2.7, 5.8]])]

In [ ]:
split_arrays=np.hsplit(sepal_matrix, [1, 2])
[arr[:2] for arr in split_arrays]

[array([[3.5],
        [3. ]]),
 array([[5.1],
        [4.9]]),
 array([], shape=(2, 0), dtype=float64)]

In [ ]:
split_arrays=np.vsplit(sepal_matrix, 2)
[arr[:2] for arr in split_arrays]

[array([[3.5, 5.1],
        [3. , 4.9]]),
 array([[3. , 6.6],
        [2.8, 6.8]])]

In [ ]:
temp_sepal = sepal_length[:5]
temp_petal = petal_length[:5]

result_broadcast = temp_sepal[:, np.newaxis] + temp_petal

print(result_broadcast)

[[6.5 6.5 6.4 6.6 6.5]
 [6.3 6.3 6.2 6.4 6.3]
 [6.1 6.1 6.  6.2 6.1]
 [6.  6.  5.9 6.1 6. ]
 [6.4 6.4 6.3 6.5 6.4]]
